services:
  - type: web
    name: fake-news-detector-ai
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars: []
    pythonVersion: "3.11"